name: fancy-resourcelinker

on: [push, pull_request]

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install the Node
      - name: Install .NET Core
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # Build library
      - name: Build library
        run: |
          npm run build

      # Execute all unit tests
      - name: Execute unit tests
        run: |
          npm test
